version: '3.1'

services:

  nats:
    image: nats-streaming:0.24.3-alpine3.15
    restart: always

  #  ORDER SERVICE

  order-service:
    build:
      context: ./order-service
    restart: always
    volumes:
      - ./docker-data/order-service:/go/src/app/data
    ports:
      - 81:80

  order-service-db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-service-db
    volumes:
      - ./docker-data/order-service-db:/var/lib/postgresql/data
      - ./order-service/initdb:/docker-entrypoint-initdb.d:ro

  order-service-db-adminer:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: order-service-db
    ports:
      - 8080:8080

  #  ORDER SENDER

  order-sender:
    build:
      context: ./order-sender
    restart: always
    ports:
      - 82:80