# Create config.yml for changes

IsProductionMode: true
APIAddress: ":80"
NATSURL: "nats://nats:4222"
ClusterID: "test-cluster"
ClientID: "order-service"
DatabaseURL: "postgres://postgres:postgres@order-service-db:5432/order-service-db"
